<?php

/*
 * This file is part of hoeringsportal-sync-files.
 *
 * (c) 2018–2019 ITK Development
 *
 * This source file is subject to the MIT license.
 */

namespace App\Command;

use App\Service\DeskproService;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class HearingOverviewCommand extends Command
{
    /** @var DeskproService */
    private $deskproService;

    public function __construct(DeskproService $deskproService)
    {
        parent::__construct();
        $this->deskproService = $deskproService;
    }

    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('app:hearing:overview');
        $this->addArgument('hearing-id', InputArgument::REQUIRED, 'The hearing id');
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        $hearingId = (int)$input->getArgument('hearing-id');
        $tickets = $this->deskproService->getHearingTickets($hearingId);

        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();

        $headers = [
            'Dato modtaget',
            'HøringID',
            'Høringssvar ID',
            'Emne',
            'Navn på afsender',
            'Udtaler sig som',
            'Evt. Navn på organisation',
            'Resume',
            'Vurdering',
        ];

        $row = 1;
        $addRow = function (array $values) use ($sheet, &$row) {
            foreach ($values as $index => $value) {
                $sheet->setCellValueByColumnAndRow($index+1, $row, $value);
            }
            $row++;
        };
        $addRow($headers);
        foreach ($tickets as $ticket) {
            $addRow([
                $ticket['date_created'],
                $ticket['fields']['hearing_id'],
                $ticket['ref'],
                $ticket['subject'],
                $ticket['person']['display_name'],
                reset($ticket['fields']['udtaler'])['title'] ?? '',
                $ticket['fields']['organization'],
                $ticket['fields']['resume'],
                $ticket['fields']['vurdering'],
            ]);
        }

        $writer = new Xlsx($spreadsheet);
        $writer->save('hello world.xlsx');
    }
}
