easy_admin:
    site_name: 'ShareFile2eDoc'

    design:
        assets:
            css:
                - 'bundles/easyadmin/app.css'
                - 'bundles/easyadmin/bootstrap-all.css'
                - 'bundles/easyadminextension/stylesheet/full-width.css'
                - 'build/easy_admin.css'

            js:
                # By default, EasyAdminBundle embeds a limited version of Bootstrap JS.
                # For collapsible form filters to work, a full version should be added:
                - 'bundles/easyadmin/bootstrap-all.js'

        menu:
            - entity: Archiver
            # - entity: User
            - entity: Log
              label: 'Error log'

            - label: 'PDF'
            - label: 'Combine'
              route: 'pdf_combine_run'

            - label: 'eDoc'
            - label: 'Item list'
              route: 'edoc_item_list'
            - entity: EdocCaseFile
            - entity: EdocDocument

    formats:
        datetime: 'd/m/Y H:i:s'

    list:
        actions: ['show']

    entities:
        Archiver:
            class: App\Entity\Archiver
            disabled_actions: ['delete']

            list:
                fields:
                    - property: name
                    - property: type
                    - property: enabled
                      type: boolean
                    - property: lastRunAt

            form:
                fields:
                    - property: name
                    - property: type
                      type: choice
                      type_options:
                          choices:
                              sharefile2edoc: !php/const App\Entity\Archiver::TYPE_SHAREFILE2EDOC
                              pdfcombine: !php/const App\Entity\Archiver::TYPE_PDF_COMBINE

                    - property: enabled
                    - property: configuration
                      type: App\Form\Type\YamlType
                      type_options:
                          schema: '%kernel.project_dir%/config/schema/archiver.configuration.schema.yaml'
                          attr:
                              rows: 20
                              cols: 80
                    - property: lastRunAt

            show:
                fields:
                    - property: name
                    - property: enabled
                    - property: lastRunAt
                    - property: configuration
                      template: admin/Archiver/show/configuration.html.twig

        User:
            class: App\Entity\User

        Log:
            class: App\Entity\ExceptionLogEntry
            disabled_actions: ['new', 'edit', 'delete']

            list:
                dql_filter: 'entity.hidden != 1'
                sort: ['createdAt', 'DESC']
                actions:
                    -
                        name: exception_log_entry_hide
                        type: route
                        label: Hide

                # form_filters:
                #     - hidden

                fields:
                    - property: createdAt
                    - property: message

            show:
                fields:
                    - property: createdAt
                    - property: message
                    - property: data
                      template: admin/ExceptionLogEntry/show/data.html.twig

        EDocLogEntry:
            class: App\Entity\EDocLogEntry
            disabled_actions: ['new', 'edit', 'delete']
            actions: ['show']

            list:
                form_filters:
                    # - archiver

                fields:
                    - property: createdAt
                    - property: archiver
                    - property: eDocCaseId
                    - property: hearingId
                    - property: replyId

        EdocCaseFile:
            label: CaseFile
            class: App\Entity\EDoc\CaseFile
            disabled_actions: ['new', 'edit', 'delete']

            list:
                form_filters:
                    # - archiver

                sort: ['updatedAt', 'DESC']

                fields:
                    - property: archiver
                    - property: caseFileIdentifier
                      template: admin/Edoc/CaseFile/list/identifier.html.twig
                    - property: shareFileItemId
                    - property: updatedAt
                    - property: createdAt

            show:
                fields:
                    - property: archiver
                    - property: caseFileIdentifier
                      template: admin/Edoc/CaseFile/list/identifier.html.twig
                    - property: shareFileItemId
                    - property: updatedAt
                    - property: createdAt
                    - property: data
                      template: admin/Edoc/show/data.html.twig

        EdocDocument:
            label: Document
            class: App\Entity\EDoc\Document
            disabled_actions: ['new', 'edit', 'delete']

            list:
                form_filters:
                    # - archiver

                sort: ['updatedAt', 'DESC']

                fields:
                    - property: archiver
                    - property: documentIdentifier
                      template: admin/Edoc/Document/list/identifier.html.twig
                    - property: shareFileItemId
                    - property: updatedAt
                    - property: createdAt

            show:
                fields:
                    - property: archiver
                    - property: documentIdentifier
                      template: admin/Edoc/Document/list/identifier.html.twig
                    - property: shareFileItemId
                    - property: updatedAt
                    - property: createdAt
                    - property: data
                      template: admin/Edoc/show/data.html.twig
